services:
  web:
    env_file:
      - .env
    container_name: fastapi_url_fold
    build:
      context: .
      dockerfile: DockerfileLocal
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16.4-alpine
    container_name: postgres_url_fold_db
    volumes:
      - postgres_url_fold_volume:/var/lib/postgresql/data/
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      - POSTGRES_PASSWORD=${SUPER_USER_PWD}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}

  # Redis DB
  redis:
    image: redis:7.4.2-alpine
    container_name: redis_db_url_fold
    volumes:
      - redis_url_fold:/data

volumes:
  postgres_url_fold_volume:
  redis_url_fold: