"""create index for  created_at field in shortened_url table

Revision ID: 1c8063288246
Revises: 278ccaefdbfe
Create Date: 2025-01-30 11:55:59.758801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Add SQLModel


# revision identifiers, used by Alembic.
revision: str = '1c8063288246'
down_revision: Union[str, None] = '278ccaefdbfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_shortened_url_created_at'), 'shortened_url', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortened_url_created_at'), table_name='shortened_url')
    # ### end Alembic commands ###
