"""Add friendly_name field to shortened_url table

Revision ID: 4e07675244ae
Revises: cb5180c3f02b
Create Date: 2025-01-09 12:36:02.951498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Add SQLModel


# revision identifiers, used by Alembic.
revision: str = '4e07675244ae'
down_revision: Union[str, None] = 'cb5180c3f02b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortened_url', sa.Column('friendly_name', sa.VARCHAR(length=40), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shortened_url', 'friendly_name')
    # ### end Alembic commands ###
