"""Add a QR code table

Revision ID: 4e779ab25e4e
Revises: 1c8063288246
Create Date: 2025-02-25 20:46:00.627739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Add SQLModel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e779ab25e4e'
down_revision: Union[str, None] = '1c8063288246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_code',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=40), nullable=False),
    sa.Column('image', sa.VARCHAR(length=2083), nullable=True),
    sa.Column('customization', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['shortened_url.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_id')
    )
    op.create_index(op.f('ix_qr_code_created_at'), 'qr_code', ['created_at'], unique=False)
    op.create_index(op.f('ix_qr_code_updated_at'), 'qr_code', ['updated_at'], unique=False)
    op.drop_constraint('shortened_url_user_id_fkey', 'shortened_url', type_='foreignkey')
    op.create_foreign_key(None, 'shortened_url', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shortened_url', type_='foreignkey')
    op.create_foreign_key('shortened_url_user_id_fkey', 'shortened_url', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_qr_code_updated_at'), table_name='qr_code')
    op.drop_index(op.f('ix_qr_code_created_at'), table_name='qr_code')
    op.drop_table('qr_code')
    # ### end Alembic commands ###
